// Generated by tools/build-client.ts — do not edit.
window.__ModuleLoader__.load({
	id: "@deepseek-ai/dsh-client-frames-ui-compat",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		const { createElement, useSyncExternalStore } = require('react')
		// ---- packages/client/frames-ui-compat/src/client/columns.ts ----
		/**
		 * The column geometry `ui-layout` used, restated.
		 *
		 * These are numbers, not types, so `import type` cannot reach them and a runtime
		 * import would drag in a package that is deliberately not mounted — `ui-layout`
		 * is disabled in this composition and its bundle pulls React in at module scope.
		 * So they are copied, and the copying is the thing to be careful about. The same
		 * goes for `computeColumns`, which is arithmetic over those numbers: the right
		 * column has to tell its occupant how wide it would be, and that answer is the
		 * shipped one rather than a new rule invented here.
		 *
		 * Source, verified in the third-party tree: `packages/client/ui-layout/src/client/columns.ts`.
		 * Both the values and the rules they encode are that file's, and this file is
		 * where a divergence would have to be recorded.
		 *
		 * Where our model disagrees with theirs is deliberate and written down: our
		 * `minPaneSize` is 72px and the collapsed rail is 56px, so the rail is below the
		 * split minimum. It is not a violation — `minPaneSize` answers "can this pane be
		 * split into two usable halves", which is a different question from "how narrow
		 * may a column be told to be".
		 */

		/** Width before any user drag, in px. */
		const SIDEBAR_DEFAULT = 280

		/** Drag clamp floor, in px. */
		const SIDEBAR_MIN = 264

		/** Drag clamp ceiling, in px. */
		const SIDEBAR_MAX = 420

		/** The closed-sidebar rail: an icon column, in px. */
		const SIDEBAR_COLLAPSED = 56

		/** Below this, the column is drawn as the rail rather than as a full column. */
		const SIDEBAR_COLLAPSED_MAX = SIDEBAR_COLLAPSED

		/**
		 * Viewport width below which the navigation column collapses to its rail.
		 *
		 * The shipped LG breakpoint (`AppFrame.tsx`: `const narrow = viewport < SIDEBAR_AUTO_COLLAPSE`).
		 * A desktop window is routinely narrower than this while a maximised browser is
		 * not, which is why a rail that ignores it looks far too wide there.
		 */
		const SIDEBAR_AUTO_COLLAPSE = 1024

		/** Right column drag clamp floor, in px. */
		const RIGHTBAR_MIN = 300

		/** First-open right panel width, as a fraction of the frame. */
		const RIGHTBAR_DEFAULT_RATIO = 0.45

		/** Largest normal right panel width, as a fraction of the frame. */
		const RIGHTBAR_MAX_RATIO = 0.7

		/** Centre width the third column protects while it is open, in px. */
		const CENTER_MIN = 400

		/** Resolved widths for one frame. */
                          
                 
                
                  
 

		/**
		 * Clamp a column width into the range the shipped shell allowed.
		 * @param px - the width asked for.
		 * @param min - the range floor.
		 * @param max - the range ceiling.
		 * @returns the clamped, whole-pixel width.
		 */
		function clampWidth(px        , min        , max        )         {
		  return Math.min(max, Math.max(min, Math.round(px)))
		}

		/**
		 * Whether a column of this width should be drawn as the compact rail.
		 * @param width - the column's rendered width in px.
		 * @returns whether the occupant should collapse.
		 */
		function isCollapsed(width        )          {
		  return width <= SIDEBAR_COLLAPSED_MAX
		}

		/**
		 * What the navigation column's width should be, in px.
		 *
		 * Ported from the shipped resolution (`AppFrame.tsx`), which is two rules:
		 *
		 * - **the preference is pixels, not a share.** `SIDEBAR_DEFAULT` is 280px and a
		 *   drag clamps it into `[SIDEBAR_MIN, SIDEBAR_MAX]`; a column sized as a
		 *   fraction of the viewport would grow with the window, which is exactly what a
		 *   column with a fixed width must not do;
		 * - **a narrow frame collapses it.** Below `SIDEBAR_AUTO_COLLAPSE` the column is
		 *   the single-column rail unless the user expanded it *while narrow*
		 *   (`stores.ts`'s `narrowExpanded`), which is a decision about this narrow frame
		 *   rather than about the width.
		 * @param viewport - the drawable width in px.
		 * @param preference - the width the user left the column at, in px.
		 * @param collapsed - whether the shell has the column collapsed.
		 * @param narrowExpanded - whether the user expanded it in a narrow frame.
		 * @returns the width in px the column should be given.
		 */
		function navWidth(
		  viewport        ,
		  preference        ,
		  collapsed         ,
		  narrowExpanded         ,
		)         {
		  const narrow = viewport < SIDEBAR_AUTO_COLLAPSE
		  const shut = narrow ? !narrowExpanded : collapsed
		  return shut ? SIDEBAR_COLLAPSED : clampWidth(preference, SIDEBAR_MIN, SIDEBAR_MAX)
		}

		/**
		 * Solve the three column widths for one viewport frame.
		 *
		 * Copied from the shipped `computeColumns` for the same reason the constants
		 * above are: it is arithmetic over numbers, `import type` cannot reach it, and a
		 * runtime import would drag in the disabled `ui-layout` bundle. One caller needs
		 * it — the right column, whose occupant is told the width it *would* take rather
		 * than the frame's current one.
		 * @param viewport - available frame width in px.
		 * @param sidebar - sidebar width preference in px (0 = closed).
		 * @param rightbar - requested right panel width in px (0 = no track).
		 * @returns actual widths: the right track shrinks, then loses its track, before
		 *   the centre drops below its minimum.
		 */
		function computeColumns(viewport        , sidebar        , rightbar        )          {
		  const s = sidebar === 0 ? SIDEBAR_COLLAPSED : clampWidth(sidebar, SIDEBAR_MIN, SIDEBAR_MAX)
		  const available = viewport - s - CENTER_MIN
		  const r = rightbar === 0 || available < RIGHTBAR_MIN
		    ? 0
		    : Math.min(available, clampWidth(rightbar, RIGHTBAR_MIN, viewport * RIGHTBAR_MAX_RATIO))
		  return { sidebar: s, center: Math.max(0, viewport - s - r), rightbar: r }
		}

		// ---- packages/client/frames-ui-compat/src/client/column-prefs.ts ----
		/**
		 * The two column widths, remembered.
		 *
		 * The shipped shell kept these in its client store (`stores.ts`: `sidebar: SIDEBAR_DEFAULT`,
		 * `rightbar: null`, `narrowExpanded: false`), and that is why its right column
		 * rarely opened at the 45% first-open default: the user had dragged it once and
		 * the preference stayed. Without somewhere to keep them, every reload gives a
		 * fresh 45% — which reads as "the columns are too wide" rather than as "the
		 * preference was forgotten".
		 *
		 * Kept in `localStorage`, the client's established medium here (the preset port
		 * uses it, `@deepseek-ai/dsh-client-store` uses it, `ui-conversation` uses it).
		 * This layer is the one that owns the geometry, so it owns the preference; the
		 * interface is injected so a test needs no browser.
		 */

		/** The storage this file writes through; `window.localStorage` satisfies it. */
                                
                                     
                                           
 

		/** Entry holding both widths and the narrow-frame decision. */
		const COLUMNS_KEY = 'dsh.frames.columns'

		/** What the shell remembers about its columns. */
                              
                                                                  
                          
                                                    
                             
     
                                                             
    
                                                                                
                                                                                 
                                                                             
     
                                  
                                                                                   
                                       
 

		/** The shape a stored record has to have to be used; anything else is ignored. */
		function parse(raw        )                       {
		  try {
		    const value          = JSON.parse(raw)
		    if (typeof value !== 'object' || value === null) return {}
		    const record = value                           
		    const number = (key        )                     =>
		      typeof record[key] === 'number' && Number.isFinite(record[key]) ? record[key]           : undefined
		    const flag = (key        )                      =>
		      typeof record[key] === 'boolean' ? record[key]            : undefined
		    return {
		      sidebar: number('sidebar'),
		      rightbar: number('rightbar'),
		      collapsed: flag('collapsed'),
		      narrowExpanded: flag('narrowExpanded'),
		    }
		  } catch {
		    // One bad byte costs a preference, not the shell: the columns open at their
		    // defaults instead of the composition failing to mount.
		    return {}
		  }
		}

		/**
		 * Read what the shell remembers, filling in the shipped defaults.
		 *
		 * Every field is optional on disk and every one has a default, so a record
		 * written by an older build (or a truncated one) still loads.
		 * @param storage - the medium, or `undefined` when there is none.
		 * @param defaults - the values to use for anything absent.
		 * @returns the preferences to start the columns from.
		 */
		function readColumnPrefs(
		  storage                           ,
		  defaults             ,
		)              {
		  const raw = storage?.getItem(COLUMNS_KEY)
		  const stored = raw === null || raw === undefined ? {} : parse(raw)
		  return {
		    sidebar: stored.sidebar ?? defaults.sidebar,
		    collapsed: stored.collapsed ?? defaults.collapsed,
		    narrowExpanded: stored.narrowExpanded ?? defaults.narrowExpanded,
		    rightbar: stored.rightbar ?? defaults.rightbar,
		  }
		}

		/**
		 * Remember the columns as they stand.
		 * @param storage - the medium, or `undefined` when there is none.
		 * @param prefs - the widths and decisions to keep.
		 */
		function writeColumnPrefs(storage                           , prefs             )       {
		  try {
		    storage?.setItem(COLUMNS_KEY, JSON.stringify(prefs))
		  } catch {
		    // A medium that refuses to write is not a reason for a resize to throw.
		  }
		}

		// ---- packages/client/frames-ui-compat/src/client/panels.ts ----
		/**
		 * Which panel the centre frame is showing.
		 *
		 * `ui-layout` kept this in its own store and the frame read it: `main` is a keyed
		 * seat, so the frame draws whichever entry the selected key names. This is that
		 * selection, over the same seat, and it belongs here rather than in the frame
		 * core — to the core the centre is one frame of one type, and what is inside it
		 * is the compatibility layer's business.
		 *
		 * Keeping it here is also what makes an unknown plugin work: a plugin that
		 * registers a `main` entry is selectable the moment it does, whether or not
		 * anyone knew about it when this layer was written.
		 */

		/** The one panel-keyed field `usePanelInfo` publishes. */
                            
                                                                 
                                       
 

		/**
		 * The seat this selection is over.
		 *
		 * Narrowed to what the selection needs, so a test can drive it with a map: the
		 * keys registered right now, and a subscription for when that set changes.
		 */
                              
                                                                                      
                           
                                                        
                                             
 

		/** The centre frame's panel selection. */
                         
                                                                                 
                          
                                             
     
                    
                                                                              
                                                                                
                     
     
                                 
                                                                            
                    
     
                                                                          
                                                                 
     
              
 

		/**
		 * Build the selection over a seat.
		 * @param source - the registered `main` keys and a subscription to them.
		 * @param conversationKey - the reserved key that means "the conversation".
		 * @returns the selection, ready to publish and to drive the frame.
		 */
		function createPanels(source             , conversationKey        )         {
		  let activePanelId                = null
		  let snapshot            = { activePanelId }
		  const listeners = new Set            ()

		  const publish = ()       => {
		    snapshot = { activePanelId }
		    for (const listener of listeners) listener()
		  }
		  const registered = (id        )          => source.keys().includes(id)

		  return {
		    getSnapshot: ()            => snapshot,
		    subscribe(listener            )             {
		      listeners.add(listener)
		      return () => { listeners.delete(listener) }
		    },

		    select(id               )       {
		      if (id !== null && !registered(id)) {
		        // The shipped message names the panel and the id; consumers match on it.
		        throw new Error(`layout.selectPanel: main panel "${id}" is not registered`)
		      }
		      if (id === activePanelId) return
		      activePanelId = id
		      publish()
		    },

		    entryKey: ()         => activePanelId ?? conversationKey,

		    sync()       {
		      if (activePanelId === null || registered(activePanelId)) return
		      activePanelId = null
		      publish()
		    },
		  }
		}

		// ---- packages/client/frames-ui-compat/src/client/rightbar.ts ----
		/**
		 * The right column: what its occupant is told, and when a frame stands for it.
		 *
		 * `ui-layout` always had a right column. It was a grid track that stayed in the
		 * DOM at 0px while the panel was hidden, so the occupant was always mounted and
		 * could say when it wanted to be shown. A frame cannot do that: `resizePane`'s
		 * floor is 2% and the engine refuses a zero share, so "hidden" cannot be a very
		 * narrow frame — it has to be no frame at all.
		 *
		 * Which splits the column in two, and this file is the seam:
		 *
		 * - the **seat** is the occupant's, and it outlives every frame: it is hosted in
		 *   `frames.overlay`, so the panel, its store and its reporting keep running
		 *   while nothing displays it;
		 * - the **frame** only reserves the space. It exists exactly while the occupant
		 *   reports that it is shown and wants a track.
		 *
		 * The numbers are the shipped ones, and the direction they travel in matters.
		 * The occupant is told the width the column *would* take if the panel were shown
		 * — never a zero because no frame is standing. `RightbarSeat` collapses itself
		 * the moment it is shown and told `canShow: false`, and its report reaches this
		 * layer a commit later than its own decision, so a width that only becomes real
		 * after the report would cancel every attempt to open the panel. The shipped
		 * shell says the same thing in `AppFrame.tsx:165-168`: eligibility must include
		 * the space before the occupant's first shown report arrives.
		 *
		 * The width this column takes comes out of the panes that can give it. That was
		 * once a deliberate difference from the shipped grid: the port's `resizePane`
		 * charged every sibling in proportion, so opening the panel also squeezed the
		 * navigation rail by a few pixels and the layer handed that back when the column
		 * closed. The rail is now declared **fixed** (`grows: false`), so the core keeps
		 * its share and charges the rest — which is what the shipped grid's
		 * `280px minmax(0, 1fr) 0` did all along. The hand-back below stays as the
		 * repair for a rail the *user* moved while the column was open, and for a rail
		 * that is not declared fixed.
		 */
                                                                                  

		/** One docked pane, as this file reads it. */
                             
                     
                                                               
                                                                           
                                                           
 

		/** What this file needs from the frame tree. */
                               
                                                                 
                                                                                
                                        
                                                               
                                        
                                                    
              
                                                                                      
                                          
   
                                             
 

		/** The type ids that play each part. */
                                     
                                                  
                        
                                                                                
                       
                                          
                            
     
                                                                                
    
                                                                               
                                                                                  
                                                                                 
                                         
     
                                   
     
                                                                                   
    
                                                                            
                                                                             
                                                                                  
                                                                                   
                   
     
                                        
                                                                              
                                    
 

		/** What the seat is handed, and how wide its own box is. */
                                      
                                    
                                                                       
                      
 

		/** The right column, as the facade and the seat see it. */
                              
     
                                                
                                                                               
                                                             
     
                            
                                                 
                 
                                                                               
                   
                                                                            
                                    
                                             
                                 
                 
 

		/**
		 * What the occupant is told for one viewport and one width preference.
		 *
		 * Exported because it is the whole of the fix in one pure function: the answer
		 * does not depend on whether a frame is standing for the column, which is what
		 * keeps the occupant's own expand from being cancelled.
		 * @param viewport - the drawable width in px.
		 * @param sidebar - the navigation column's width in px, 0 when it is closed.
		 * @param preference - the width the panel was last left at, or `undefined`
		 *   before it was ever shown.
		 * @returns the width the column would take, and whether there is room for it.
		 */
		function rightbarOwner(viewport        , sidebar        , preference                    )                     {
		  const wanted = preference ?? viewport * RIGHTBAR_DEFAULT_RATIO
		  const columns = computeColumns(viewport, sidebar, wanted)
		  // Whole pixels: this is handed to a stylesheet, and a fraction of a pixel there
		  // is only noise the comparisons above would then have to tolerate.
		  return { width: Math.round(columns.rightbar), viewportWidth: viewport, canShow: columns.rightbar > 0 }
		}

		/**
		 * The share to ask the core for, corrected by what the last ask produced.
		 *
		 * `resizePane` takes a share of the pane's *parent split*, and this layer cannot
		 * know which split that is: a column opened beside a centre the user has already
		 * split becomes a child of that inner split, not of the window. Rather than
		 * guess, the caller asks in window fractions, measures what came back, and
		 * scales the ask by the ratio — which divides the parent's width back out.
		 * @param wanted - the width in px the column should have.
		 * @param measured - the width in px the last ask produced.
		 * @param asked - the share that produced it.
		 * @returns the share to ask for.
		 */
		function columnShare(wanted        , measured        , asked        )         {
		  if (!(measured > 0) || !Number.isFinite(measured) || !(asked > 0)) return asked
		  return asked * (wanted / measured)
		}

		/**
		 * Build the column over a frame tree.
		 * @param frames - the tree, through the service the renderer published.
		 * @param options - the type ids that play each part.
		 * @returns the column, already following the tree.
		 */
		function createRightColumn(frames              , options                    )              {
		  /**
		   * The width the panel was last left at, in px.
		   *
		   * Seeded from what the shell remembered, so a reload comes back to the width
		   * the user dragged to — the shipped store did the same, which is why its 45%
		   * first-open default was rarely what anyone saw. Set on first show when there is
		   * nothing remembered.
		   */
		  let preference                     = options.initialPreference
		  /** What the occupant last reported: shown at all, and whether it wants a track. */
		  let shown = false
		  let track = false
		  /** Whether the last attempt to stand a frame up was refused (no room, mostly). */
		  let refused = false
		  /** The viewport and the width this layer last left the frame at. */
		  let lastViewport                    
		  let lastAsked                    
		  /** The pane this layer opened for the column. Never a pane the user made. */
		  let columnPane                    
		  /** What the navigation column had before the third column took room. */
		  let navRestore                                                             

		  let listeners = new Set            ()
		  let reconciling = false
		  let snapshot                      = { owner: rightbarOwner(0, 0, undefined), box: 0 }

		  /** The pane holding a type, if the tree has one. */
		  const paneFor = (docked                       , typeId        )                         =>
		    docked.find((pane) => pane.content?.typeId === typeId)

		  const widthOf = (pane                        , viewport        )         =>
		    // Whole pixels, because the same number is handed to a stylesheet as a width
		    // and compared against what was asked for.
		    pane === undefined ? 0 : Math.round(pane.rect.width * viewport)

		  /**
		   * The pane the plugin body stood up as the navigation column.
		   *
		   * Deliberately not "whichever pane shows the navigation type": the shell has to
		   * register that content for a frame to display it, so the picker offers it, and
		   * a user who puts a navigation panel in a frame of their own would otherwise
		   * have this layer measuring and resizing *their* frame as if it were the rail.
		   * @param docked - the projection's panes.
		   * @returns the rail's pane, or undefined when the shell has none.
		   */
		  const navOf = (docked                       )                         => {
		    const id = options.navPane()
		    return id === undefined ? undefined : docked.find((pane) => pane.id === id)
		  }

		  /** The pane that already reaches furthest right, which is where a column goes. */
		  const rightmost = (docked                       )                         =>
		    docked.reduce                        (
		      (best, pane) => best === undefined || pane.rect.x + pane.rect.width > best.rect.x + best.rect.width ? pane : best,
		      undefined,
		    )

		  /** The width the navigation column takes out of the window, 0 when it is closed. */
		  const sidebarWidth = (view                                     , viewport        )         =>
		    widthOf(navOf(view.docked), viewport)

		  /**
		   * The pane standing for the column: the one this layer opened, and only that
		   * one.
		   *
		   * Deliberately not "whichever pane shows the column's content". The shell
		   * registers that content — it has to, since a frame displays a content — so the
		   * picker offers it, and a user who puts it in a pane of their own would find
		   * this layer resizing and closing it. Which pane is the column is this layer's
		   * arrangement, so it remembers it.
		   * @param docked - the projection's panes.
		   * @returns the column's pane, or undefined when there is none.
		   */
		  const columnOf = (docked                       )                         => {
		    if (columnPane === undefined) return undefined
		    const found = docked.find((candidate) => candidate.id === columnPane)
		    // The tree dropped it — closed by a gesture, or by a preset that does not
		    // include it. The next reconciliation may stand one up again.
		    if (found === undefined) columnPane = undefined
		    return found
		  }

		  /** What the occupant is told right now. */
		  const ownerNow = ()                      => {
		    const view = frames.project()
		    const viewport = view.viewport?.width ?? 0
		    const pane = columnOf(view.docked)
		    const solved = rightbarOwner(viewport, sidebarWidth(view, viewport), preference)
		    // While a frame stands for the column, that frame *is* the width: the panel
		    // and the column have to agree to the pixel, and whatever moved the frame
		    // (a drag, the sidebar taking room back) moved the column with it.
		    const width = pane === undefined ? solved.width : widthOf(pane, viewport)
		    return {
		      owner: { width, viewportWidth: viewport, canShow: solved.canShow && !refused },
		      box: shown && track && !refused ? width : 0,
		    }
		  }

		  /** Publish what the seat draws from: a fresh object only when it says something new. */
		  const publish = ()       => {
		    const next = ownerNow()
		    const { owner, box } = next
		    if (snapshot.owner.width === owner.width && snapshot.owner.viewportWidth === owner.viewportWidth
		      && snapshot.owner.canShow === owner.canShow && snapshot.box === box) return
		    snapshot = next
		    for (const listener of listeners) listener()
		  }

		  /**
		   * Take the column down and hand the navigation column its room back.
		   *
		   * Only a navigation column that came out *narrower* than it went in is
		   * repaired, and only down to its own contract floor: a width the user chose
		   * while the panel was open is theirs to keep, and a rail that was collapsed
		   * stays a rail.
		   * @param pane - the pane standing for the column.
		   * @param viewport - the drawable width in px.
		   */
		  const closeColumn = (pane            , viewport        )       => {
		    frames.close(pane.id)
		    columnPane = undefined
		    const record = navRestore
		    navRestore = undefined
		    if (record === undefined) return
		    const navigation = navOf(frames.project().docked)
		    if (navigation === undefined) return
		    const current = widthOf(navigation, viewport)
		    // A rail stays a rail: the occupant collapsed it while the panel was open,
		    // and that is a decision, not a concession to undo.
		    if (current <= SIDEBAR_COLLAPSED) return
		    const floor = record.width <= SIDEBAR_COLLAPSED
		      ? record.width
		      : clampWidth(record.width, SIDEBAR_MIN, SIDEBAR_MAX)
		    if (current >= floor - 1) return
		    frames.resizePane(navigation.id, floor / viewport)
		  }

		  /** Stand a frame up for the column, or take the standing one down. */
		  const settle = ()       => {
		    const view = frames.project()
		    const viewport = view.viewport?.width
		    if (viewport === undefined || viewport <= 0) return

		    const sameViewport = lastViewport === viewport
		    const navigation = navOf(view.docked)
		    let pane = columnOf(view.docked)
		    // The first time the panel is shown it opens at the shipped width, kept from
		    // then on so reopening comes back to the width the user left.
		    if (shown && track) preference ??= Math.max(RIGHTBAR_MIN, Math.round(viewport * RIGHTBAR_DEFAULT_RATIO))

		    if (pane !== undefined && sameViewport && lastAsked !== undefined) {
		      const measured = widthOf(pane, viewport)
		      if (Math.abs(measured - lastAsked) > 1) {
		        // Someone else moved it: a divider drag, a preset, the navigation column
		        // taking room back. That is the width now, clamped the way the shipped
		        // `setRightbar` clamped it — and remembered, so it is the width next time
		        // rather than a fresh 45% of whatever the frame happens to be.
		        preference = clampWidth(measured, RIGHTBAR_MIN, Math.max(RIGHTBAR_MIN, viewport * RIGHTBAR_MAX_RATIO))
		        lastAsked = preference
		        options.remember?.(preference)
		      }
		    }
		    const resizedViewport = lastViewport !== undefined && !sameViewport
		    lastViewport = viewport

		    if (!shown || !track || rightbarOwner(viewport, sidebarWidth(view, viewport), preference).width <= 0) {
		      // No column: the occupant keeps running in the overlay, and the centre
		      // takes the width back.
		      if (pane !== undefined) closeColumn(pane, viewport)
		      else navRestore = undefined
		      lastAsked = undefined
		      refused = false
		      return
		    }

		    if (pane === undefined) {
		      // Beside whatever already reaches the window's right edge: the shipped
		      // grid's third column was always the outermost one, and the seat draws
		      // itself against that edge. At boot that is the centre, which is why this
		      // is the same placement `beside: centre` would give.
		      const beside = rightmost(view.docked)
		      const before = new Set(view.docked.map((candidate) => candidate.id))
		      // A split, not `openContent`: opening a content de-duplicates by identity
		      // and would focus a pane the *user* put that content in — the picker offers
		      // it, so that is a reachable state — leaving this layer to size a pane that
		      // is not its column. A split always makes the column, and the content it
		      // seats is the one registered for it.
		      const opened = frames.split(beside?.id, options.rightbarTypeId, 'row')
		      if (!opened.ok) {
		        refused = true
		        return
		      }
		      refused = false
		      // Opening a frame focuses it, and the shell belongs on its content — the
		      // same repair the sidebar's seeding makes.
		      const afterOpen = frames.project()
		      const openedCentre = paneFor(afterOpen.docked, options.conversationTypeId)
		      if (openedCentre !== undefined) frames.focus(openedCentre.id)
		      // The pane that was not there a moment ago is the column, and this is the
		      // only place that decides so.
		      pane = afterOpen.docked.find((candidate) => !before.has(candidate.id))
		      if (pane === undefined) return
		      columnPane = pane.id
		      lastAsked = undefined
		    }

		    // While the column is open at this viewport its frame is the width, so
		    // nothing here re-asserts it: a drag, or a sibling giving room, is not undone
		    // on the next change. A viewport that changed is different — then the
		    // remembered width is solved again against it.
		    const wanted = resizedViewport || lastAsked === undefined
		      ? rightbarOwner(viewport, sidebarWidth(view, viewport), preference).width
		      : lastAsked
		    if (navigation !== undefined && navRestore === undefined) {
		      // Taken once per column, not per change: it is what the navigation column
		      // had before this column started taking room, so it must not be read back
		      // after the concession it is meant to undo.
		      navRestore = { id: navigation.id, width: widthOf(navigation, viewport) }
		    }
		    const measured = widthOf(pane, viewport)
		    if (Math.abs(measured - wanted) > 1) {
		      const asked = wanted / viewport
		      frames.resizePane(pane.id, asked)
		      // Ask in window fractions, measure what came back, and correct once: the
		      // pane's parent split is not necessarily the window (see `columnShare`).
		      // Measured through the pane this layer opened, not through the type: the
		      // picker offers the content, so a pane showing it may be the user's.
		      const landed = widthOf(columnOf(frames.project().docked), viewport)
		      if (landed > 0 && Math.abs(landed - wanted) > 1) {
		        const corrected = columnOf(frames.project().docked)
		        if (corrected !== undefined) frames.resizePane(corrected.id, columnShare(wanted, landed, asked))
		      }
		    }
		    lastAsked = widthOf(columnOf(frames.project().docked), viewport)
		  }

		  const reconcile = ()       => {
		    // The service notifies synchronously, so this reconciles re-entrantly from
		    // its own writes; one pass is the whole of the work.
		    if (reconciling) return
		    reconciling = true
		    try {
		      settle()
		      publish()
		    } finally {
		      reconciling = false
		    }
		  }

		  const off = frames.subscribe(() => {
		    if (reconciling) return
		    reconcile()
		  })

		  const column              = {
		    show(wantsTrack         )       {
		      shown = true
		      track = wantsTrack
		      reconcile()
		    },
		    dismiss()       {
		      shown = false
		      reconcile()
		    },
		    reconcile,
		    getSnapshot: ()                      => snapshot,
		    subscribe(listener            )             {
		      listeners.add(listener)
		      return () => { listeners.delete(listener) }
		    },
		    dispose()       {
		      off()
		      listeners = new Set()
		    },
		  }

		  // The seat is mounted before any of this is reported, so the published value
		  // has to be right from the first read rather than from the first change.
		  reconcile()
		  return column
		}

		// ---- packages/client/frames-ui-compat/src/client/columns-body.ts ----
		/**
		 * The column bodies: the sidebar's seat, and the empty box the right column's
		 * frame reserves.
		 *
		 * `ui-layout` drew a three-track grid — sidebar, centre, rightbar — and handed
		 * each column's occupant a share of the geometry it had solved. There is no grid
		 * here: each column is a frame, its area is the frame's area, and the width the
		 * occupant is told is that area measured against the viewport.
		 *
		 * That conversion is this file's whole job, and it has to be exact in both
		 * directions — a body is told how many pixels wide it is, and when the column is
		 * asked for a width the core is told the share of the parent that comes to.
		 *
		 * The two columns differ in one thing, and it decides where each seat is drawn.
		 * The sidebar's frame is always there, so its seat is drawn inside it. The right
		 * column's frame exists only while the panel is shown, so its seat is hosted on
		 * the overlay layer instead (`./overlay-body.ts`) and this frame reserves the
		 * width. See `./rightbar.ts` for why that split is not optional.
		 */


		/** What a frame body is handed: what every renderer gives, plus its own children. */
                                                         
                                                                                  
 

		/**
		 * The left column.
		 *
		 * `ui-sidebar` is the only occupant. It reads `collapsed` to decide between the
		 * full column and the compact rail, and `width` to lay itself out — so both have
		 * to come from the frame the column is drawn in, which is why the renderer hands
		 * a body its own rectangle.
		 * @param props - the frame's area, the viewport, and the child renderer.
		 * @returns the sidebar seat, or nothing when no plugin has taken it.
		 */
		function LegacySidebar({ renderSlot, rect, viewport }                 )          {
		  const width = rect.width * viewport.width
		  const owner                    = { width, collapsed: isCollapsed(width) }
		  return renderSlot('sidebar', owner)
		}

		/**
		 * The frame the right column reserves, drawn empty.
		 *
		 * The panel is deliberately not drawn here: it belongs to the seat on the overlay
		 * layer, which is mounted for as long as the content exists rather than for as
		 * long as this frame does. This body exists so the pane shows the empty room the
		 * occupant positions itself in — a body that returned nothing would be replaced
		 * by the renderer's title fallback, and the column would read as a labelled empty
		 * box.
		 * @returns the box that fills the frame.
		 */
		function LegacyRightColumnPane()          {
		  return createElement('div', { style: { flex: '1 1 auto', minHeight: 0 } })
		}

		// ---- packages/client/frames-ui-compat/src/client/overlay-body.ts ----
		/**
		 * The legacy overlay layer: the seats that have to be drawn whether or not any
		 * frame exists.
		 *
		 * `ui-layout` had one such layer — the shell's overlay track, rendered by
		 * `AppFrame` outside the grid — and the right column is the other thing that
		 * needs one. They are the same requirement, so they are the same entry: the
		 * renderer draws `frames.overlay` once, always, and this is what it puts there.
		 *
		 * The right column is here rather than in its own frame's body because the loop
		 * would otherwise close on itself: the frame is opened *because* the occupant
		 * reported that it was shown, and the occupant only reports from inside a frame
		 * that is being drawn. `frames.overlay` is drawn either way, so the seat is
		 * mounted from the moment this plugin is, and the frame is left with one job it
		 * can still do while the panel is hidden — reserving the width. `./rightbar.ts`
		 * owns the numbers that decide that; this file only draws them.
		 */

		/** Props a registration adds to its component, alongside the seat's own. */
                                        
                                                             
                              
 

		/**
		 * The hairline on the column's inner edge.
		 *
		 * The renderer draws one at every frame boundary, but it cannot draw *this* one:
		 * the column's pixels are painted here rather than in the frame's body, and this
		 * layer sits above the renderer's lines, so the line under the panel is covered —
		 * which is exactly what "no boundary between the conversation and the right
		 * column" looked like. The shipped shell has the same arrangement and the same
		 * answer, written in its stylesheet: *the occupant draws its own left border*.
		 * This is that border. It reads the same token the renderer's lines do.
		 */
		const BOUNDARY = 'var(--dsw-alias-border-l3, #39404c)'

		/**
		 * The layer's entry: the right column, then whatever the shell hangs over
		 * everything.
		 *
		 * Order matters and is deliberate. The column comes first so the shell's overlays
		 * — a dialog, a toast — paint over it, which is the stacking the shipped frame
		 * had (the right column below the overlays, the overlays below floating panels).
		 * @param props - the right column and the child renderers.
		 * @returns the layer's contents.
		 */
		function LegacyOverlay({ column, renderSlot }                           
                                                     
                                                          
		 )          {
		  const { owner, box }                      = useSyncExternalStore(column.subscribe, column.getSnapshot)
		  return createElement('div', { style: { position: 'absolute', inset: '0' } },
		    // The occupant positions itself inside this box — the shipped panel is
		    // absolute at the column's right edge — so the box is the column's width, and
		    // 0 while the panel is hidden. A zero-width box draws nothing and swallows no
		    // clicks, which is what makes being hidden cost nothing.
		    createElement('div', {
		      key: 'rightbar',
		      style: {
		        position: 'absolute',
		        top: '0',
		        right: '0',
		        bottom: '0',
		        width: `${box}px`,
		        overflow: 'hidden',
		        // The layer takes no pointer events of its own; this is the part of it
		        // that does, because a panel nobody can click is not a panel.
		        pointerEvents: 'auto',
		        // The boundary between the centre and this column (see `BOUNDARY`), drawn
		        // only while the column is standing: a zero-width box is what "hidden"
		        // looks like, and hidden means there is no boundary here at all.
		        //
		        // `content-box` is load-bearing. The panel has to keep the exact width the
		        // column has — that agreement is what the column's arithmetic is for — so
		        // the border sits in the pixel this box takes from the centre, not in one
		        // of the panel's own.
		        boxSizing: 'content-box',
		        borderLeft: box > 0 ? `1px solid ${BOUNDARY}` : undefined,
		      },
		    }, renderSlot('rightbar', owner)),
		    createElement('div', { key: 'shell.overlay' }, renderSlot('shell.overlay', {})),
		  )
		}

		// ---- packages/client/frames-ui-compat/src/client/facade.ts ----
		/**
		 * The `ctx.layout` facade.
		 *
		 * `ui-layout` cannot be edited, so this reproduces its runtime interface over the
		 * frame tree instead of migrating its consumers. `ui-workspace`, `ui-sidebar` and
		 * `ui-sidebar-right` inject the service and call into it; nothing about them
		 * changes.
		 *
		 * Three of the five calls need saying more precisely than the interface does:
		 *
		 * - `toggleSidebar()` toggles the sidebar between *collapsed* and *expanded*, not
		 *   between present and absent. In the shipped grid the column never disappeared:
		 *   it shrank to a 56px rail and the occupant drew a compact version of itself.
		 *   Here that is a frame whose share changes, so the frame — and with it every
		 *   seat `ui-sidebar` declares — stays mounted. That is what makes collapsing
		 *   safe, and it is the whole reason the content registry exists.
		 * - `openRightbar()` and `closeRightbar()` are **reports, not commands**. The
		 *   occupant decides whether it is shown and tells the frame how much room to
		 *   reserve; the interface says as much. So this facade takes the occupant at its
		 *   word and hands the report to the right column, which owns the numbers and the
		 *   frame that reserves them (`./rightbar.ts`).
		 * - the sidebar's own geometry is still this file's, because its column never
		 *   disappears and so its frame is always there to resize.
		 *
		 * The facade is pure over a frame tree and a viewport, so it is testable without
		 * a browser.
		 */
                                         
                                                

		/** One docked frame as the facade reads it. */
                             
                     
                                           
                                                                           
                                                           
 

		/** What the facade needs from the frame tree. */
                               
                                                               
                                                                                 
              
                                                                                      
                                          
   
 

		/** How the facade addresses the tree. */
                                      
                                                   
                       
                                                 
                
                                                                                  
                     
     
                                              
    
                                                                               
                                                              
                                                                             
                                                                               
                                                                            
     
                           
 

		/** The panel-navigation and geometry actions `ui-layout` exposed as `ctx.layout`. */
                               
                                           
                                
                       
                                                         
                       
 

		/**
		 * Build the facade.
		 *
		 * Three behaviours are load-bearing because the shipped implementation has them
		 * and its consumers may rely on them:
		 *
		 * - `selectPanel` with an unregistered id throws and leaves the current selection
		 *   alone;
		 * - any accepted selection aborts the navigation signal a caller is holding,
		 *   which is how a pending navigation learns it lost;
		 * - the sidebar toggle flips the *collapsed* state, so a collapse followed by an
		 *   expand comes back to the width the user had chosen rather than to the default
		 *   — the plugin body resolves it, because the width rules need the viewport.
		 * @param options - the type ids that play each column, and how to toggle the rail.
		 * @returns the facade.
		 */
		function createLayoutFacade(options                     )               {
		  let navigation                             

		  const beginNavigation = ()              => {
		    navigation?.abort()
		    navigation = new AbortController()
		    return navigation.signal
		  }

		  const selectPanel = (panelId               )       => {
		    // The selection is this layer's, not the tree's: to the core the centre is
		    // one frame of one type, and which panel is inside it is nobody's business
		    // but ours. Throws before the navigation signal is touched, so a rejected
		    // selection leaves a pending navigation alone.
		    options.panels.select(panelId)
		    beginNavigation()
		  }

		  const toggleSidebar = ()       => {
		    options.toggleSidebar()
		  }

		  const openRightbar = (track         , _fullscreen         )       => {
		    // A report, not a command: the occupant says it is displayed, and whether it
		    // wants a column reserved for it. `fullscreen` needs nothing from this layer
		    // — a panel that covers the viewport presents itself that way, which is the
		    // same division the shipped grid had (`track ? pref : 0` for the track).
		    options.column.show(track)
		  }

		  const closeRightbar = ()       => {
		    // Also a report: the occupant says it is hidden. The column goes away and
		    // the content stays.
		    options.column.dismiss()
		  }

		  return { selectPanel, beginNavigation, toggleSidebar, openRightbar, closeRightbar }
		}

		// ---- packages/client/frames-ui-compat/src/client/theme-presenter.ts ----
		/**
		 * Theme presentation, reproduced from `ui-layout`.
		 *
		 * `ui-layout` owns the only code that writes a resolved theme snapshot to the
		 * document, and it cannot be edited, so disabling it would leave the page
		 * unthemed. This is that behaviour, copied rather than reinvented: pure DOM
		 * writes, no React path, and a retraction set so foreign attributes, metadata,
		 * and inline styles survive.
		 */
                                                                            

		/** Body attribute selecting the dark base palette in the token stylesheets. */
		const DARK_ATTRIBUTE = 'data-ds-dark-theme'

		/** Body variable carrying the user's content font size in px. */
		const CONTENT_FONT_SIZE_VARIABLE = '--dsh-content-font-size'

		/** Applies theme snapshots to the document; one instance per plugin fiber. */
		class ThemePresenter {
		  /** Token names written by the last apply, which is this presenter's retraction set. */
		          appliedTokens           = []
		  /** The single metadata node this presenter inserts and removes. */
		                   themeColorMeta                 

		  /** Create the presenter-owned metadata node before the first snapshot arrives. */
		  constructor() {
		    this.themeColorMeta = document.createElement('meta')
		    this.themeColorMeta.name = 'theme-color'
		  }

		  /**
		   * Project a snapshot onto the document.
		   * @param snapshot - resolved theme snapshot from `ctx.theme`.
		   */
		  apply(snapshot               )       {
		    const scheme = snapshot.active.colorScheme
		    document.documentElement.style.colorScheme = scheme
		    const body = document.body
		    if (scheme === 'dark') body.setAttribute(DARK_ATTRIBUTE, '')
		    else body.removeAttribute(DARK_ATTRIBUTE)
		    body.style.setProperty(CONTENT_FONT_SIZE_VARIABLE, `${snapshot.fontSize}px`)
		    for (const name of this.appliedTokens) body.style.removeProperty(name)
		    this.appliedTokens = []
		    for (const [name, value] of Object.entries(snapshot.active.tokens)) {
		      body.style.setProperty(name, value)
		      this.appliedTokens.push(name)
		    }
		    // Read the rendered background after the writes, so the palette stays the
		    // single colour authority.
		    this.themeColorMeta.content = getComputedStyle(body).backgroundColor
		    if (!this.themeColorMeta.isConnected) document.head.append(this.themeColorMeta)
		  }

		  /** Retract everything this presenter wrote, and only that. */
		  dispose()       {
		    document.documentElement.style.removeProperty('color-scheme')
		    const body = document.body
		    body.removeAttribute(DARK_ATTRIBUTE)
		    body.style.removeProperty(CONTENT_FONT_SIZE_VARIABLE)
		    for (const name of this.appliedTokens) body.style.removeProperty(name)
		    this.appliedTokens = []
		    this.themeColorMeta.remove()
		  }
		}

		// ---- packages/client/frames-ui-compat/src/client/index.ts ----
		/**
		 * The compatibility layer's plugin body.
		 *
		 * `ui-layout` cannot be edited, so this stands in for it: it provides
		 * `ctx.layout`, supplies the `usePanelInfo` standard prop, presents the theme to
		 * the document, and registers the frame bodies that declare the legacy seats.
		 *
		 * The last part is the bridge. A registration may declare child slots, so
		 * declaring `main` here makes `ui-conversation`'s existing
		 * `slots.inject('main', …)` fire and its panel render inside a frame — with no
		 * edit to `ui-conversation`.
		 */








		/** Services this plugin needs before it activates. */
		const inject = ['slots', 'theme', 'locale', 'frames']

		/**
		 * The browser medium, when there is one.
		 *
		 * The same guard the renderer's preset port uses: a non-browser boot of this
		 * bundle has no `localStorage`, and a shell that cannot remember its column
		 * widths is not a shell that fails to start.
		 * @returns the storage, or `undefined` when there is none.
		 */
		function columnStorage()                            {
		  try {
		    return typeof localStorage === 'undefined' ? undefined : localStorage                 
		  } catch {
		    // Reaching `localStorage` can throw outright when a document is sandboxed
		    // without `allow-same-origin`.
		    return undefined
		  }
		}

		/** The frame types the bridge supplies, and the legacy keys they answer to. */
		const CONVERSATION_TYPE = 'legacy.conversation'
		const CONVERSATION_KEY = 'conversation'
		const SIDEBAR_TYPE = 'legacy.sidebar'
		const RIGHTBAR_TYPE = 'legacy.rightbar'

		/** Props a registration adds to its component, alongside the seat's own. */
                          
                
 

		/** Props the bridge's component receives: the selection and the child renderer. */
                                              
                                                                                
 

		/**
		 * The frame body that carries the centre.
		 *
		 * `main` is a keyed seat, so which panel shows is a key: the reserved
		 * conversation key, or whatever the sidebar selected. Choosing it *here*, inside
		 * one frame, is what lets any plugin register a panel and be selectable without
		 * the frame core ever hearing about panels — and it is why this layer keeps the
		 * selection rather than asking the core for it.
		 * @param props - the selection and the child renderer for `main`.
		 * @returns the selected panel.
		 */
		function LegacyConversation({ panels, renderSlot }             )          {
		  return renderSlot('main', {}, { entryKey: panels.entryKey() })
		}

		/**
		 * Register the compatibility layer.
		 * @param ctx - the client context.
		 */
		function apply(ctx   
                                                            
                 
          
                                                            
                                                           
                                          
                                                                                   
                                                                  
                                               
                                                            
   
                                                               
                                                                                                             
                                                                
                                                                            
                            
		 )       {
		  ctx.effect(() => {
		    const frames = ctx.get('frames')     
                                           
                                                                                    
                                                                                                    
                                            
                                            
                                                                   
                                        
                                     
                                      
                                
                  
                           
                                                                                                   
              
                                                                                            
                                                 
                  
                                                                                          
                                   
                             
                                                                       
                                                                   
           
       
     
		    frames.registerType({ id: CONVERSATION_TYPE, title: () => 'Conversation' })
		    // The navigation column has a fixed width and cannot be split.
		    //
		    // `grows: false` is the whole of "fixed": the column neither absorbs room a
		    // departing sibling frees nor concedes room when a sibling asks for some, so
		    // it stays 280px (or 56px collapsed) while the right column opens and closes
		    // — which is what the shipped grid did, squeezing only the centre. `splittable:
		    // false` refuses a split whose reference frame is the rail: half a rail is not
		    // a thing, and the shell has one navigation column.
		    //
		    // It used to refuse the close gesture as well, and that was wrong twice over.
		    // A policy is a property of the *type*, so it refused every frame displaying
		    // a navigation panel — including one the user made from the picker, which
		    // then could not be closed at all. And its reason ("nothing can bring this
		    // column back") stopped being true once this layer's seeding became a
		    // reconciliation: standing the column up again is exactly what the code below
		    // does, which is the same arrangement the right column already has.
		    frames.registerType({
		      id: SIDEBAR_TYPE,
		      title: () => 'Navigation',
		      policy: { grows: false, splittable: false },
		    })
		    // The right column is closable, and has to be: closing its frame is exactly
		    // what "hidden" means here. A close that arrives from anywhere else is
		    // repaired by the column's next reconciliation, because whether the panel is
		    // shown is its occupant's decision and not a frame manager's.
		    //
		    // It is also not placeable, which is the one thing about this column the core
		    // has to know. Its panel is mounted on the overlay layer and drawn by this
		    // layer at whatever width the column has — the frame only reserves that width
		    // and draws an empty box. So a frame of the user's own displaying this content
		    // could not show anything: the picker would be offering an empty box. The
		    // sidebar stays placeable, because its own body does draw its seat.
		    frames.registerType({ id: RIGHTBAR_TYPE, title: () => 'Right panel', policy: { placeable: false } })
		    // A column has to be able to exist with no frame showing it — the sidebar is
		    // closed by shrinking to the rail, and the right panel is closed by its
		    // occupant deciding so. Registering the contents up front is what lets either
		    // come back without being recreated.
		    frames.registerContent({ id: SIDEBAR_TYPE, kind: SIDEBAR_TYPE, title: 'Navigation' })
		    frames.registerContent({ id: RIGHTBAR_TYPE, kind: RIGHTBAR_TYPE, title: 'Right panel' })

		    // Which panel the centre shows is this layer's own state, over the `main`
		    // seat. It is deliberately not derived from the frame tree: to the core the
		    // centre is one frame of one type.
		    //
		    // The selection's snapshot keeps its identity between changes, because
		    // `useSyncExternalStore` compares by reference and a freshly built object on
		    // every read would re-render forever.
		    const panels = createPanels({
		      keys: () => ctx.slots.entries('main').flatMap((entry) => {
		        const key = (entry.options                     ).key
		        return typeof key === 'string' ? [key] : []
		      }),
		      subscribe: (listener) => ctx.slots.subscribe('main', listener),
		    }, CONVERSATION_KEY)
		    // A panel whose plugin went away must not leave the centre drawing nothing.
		    const offPanels = ctx.slots.subscribe('main', () => { panels.sync() })

		    // The pane this layer stands the navigation column up in. Kept because "which
		    // pane shows a navigation panel" and "which pane is the navigation column" are
		    // different questions: the picker offers the content, so a user can put a
		    // navigation panel in a frame of their own, and that frame is none of this
		    // layer's business — the same distinction the right column learned first.
		    let navPane                    

		    // The right column is two things, and `./rightbar.ts` owns both: a seat that
		    // outlives every frame, and the frame that reserves its width while the
		    // occupant reports that it is shown. It is handed the navigation column's
		    // pane for the same reason: the rail's width is room taken out of the window,
		    // and the room was taken from *that* frame.
		    /**
		     * What the shell remembers about its two columns.
		     *
		     * Read at mount and written on every decision, so a width the user chose
		     * survives a reload. The shipped shell kept these in its client store, and
		     * that is why its right column rarely opened at the 45% first-open default:
		     * the preference stayed. Without this, every reload gives a fresh 45% of
		     * whatever the window happens to be — which reads as "the columns are too
		     * wide" rather than as "the preference was forgotten".
		     */
		    const prefs   
                     
                        
                             
                                  
		      = {
		      ...readColumnPrefs(columnStorage(), {
		        sidebar: SIDEBAR_DEFAULT,
		        collapsed: false,
		        narrowExpanded: false,
		        rightbar: undefined,
		      }),
		    }
		    const remember = ()       => { writeColumnPrefs(columnStorage(), prefs) }

		    /** How wide the navigation column should be, in px, for this viewport. */
		    const railWidth = (viewport        )         =>
		      navWidth(viewport, prefs.sidebar, prefs.collapsed, prefs.narrowExpanded)

		    /** A pane's width in whole pixels. */
		    const pxOf = (pane                                               , viewport        )         =>
		      Math.round(pane.rect.width * viewport)

		    const column = createRightColumn(frames, {
		      rightbarTypeId: RIGHTBAR_TYPE,
		      sidebarTypeId: SIDEBAR_TYPE,
		      conversationTypeId: CONVERSATION_TYPE,
		      navPane: () => navPane,
		      // Where the width it opens at comes from, and where a width the user
		      // dragged it to goes.
		      initialPreference: prefs.rightbar,
		      remember: (width) => { prefs.rightbar = width; remember() },
		    })

		    const facade = createLayoutFacade({
		      sidebarTypeId: SIDEBAR_TYPE,
		      panels,
		      column,
		      // The width rules — the auto-collapse breakpoint and the narrow-frame
		      // decision — live with the rest of the column geometry, so the toggle is
		      // resolved here rather than in the facade.
		      toggleSidebar: () => {
		        const width = frames.project().viewport?.width
		        if (width === undefined) return
		        if (width < SIDEBAR_AUTO_COLLAPSE) prefs.narrowExpanded = !prefs.narrowExpanded
		        else prefs.collapsed = !prefs.collapsed
		        remember()
		        reconcileNavigation()
		      },
		    })

		    const dropPanelInfo = ctx.slots.provideRoot({ hooks: { panelInfo: panels } })
		    const dropService = ctx.reflect.provide('layout', facade)

		    // The sidebar goes up with the shell. `ui-sidebar` cannot put its own column
		    // there — it renders into a seat, and a seat needs a frame to be drawn in —
		    // so whoever owns the column types owns the opening. This is that: the
		    // composition, which is the only layer that knows these three types exist.
		    //
		    // The right column is *not* opened here, and no longer needs to be. Its seat
		    // is mounted with this plugin (below), so the occupant reports its own
		    // presentation from boot: it says "hidden" until someone expands it, and the
		    // column appears, resizes itself and goes away again on those reports. The
		    // shipped shell opened onto no right column either.
		    //
		    // The core default is still one frame. A profile that mounts no compatibility
		    // layer gets exactly that, which is what "one frame with nothing configured"
		    // has always meant.
		    /**
		     * Stand the navigation column up when the shell has none, and keep it the
		     * width the user last left it at.
		     *
		     * A reconciliation rather than a one-shot seeding, because the column is now
		     * closable: `C-x C-d` on it is accepted (the close gesture is the user's, and
		     * a frame they can see must not refuse it) and this is what puts the column
		     * back. It asks for the column only when **nothing anywhere** is displaying
		     * the navigation content, which keeps the promise the shell makes — the
		     * navigation panel is always on screen in some frame — without standing a
		     * second copy of it beside the one a user made.
		     *
		     * The width is applied on every pass, and that is what makes it a *width*
		     * rather than a share: the tree stores a fraction of the viewport, so a rail
		     * sized once from a 1000px window comes back 538px wide in a 1920px one.
		     * Re-asking for the remembered pixels is also what makes the narrow-frame
		     * rule stick (below `SIDEBAR_AUTO_COLLAPSE` the column is the 56px rail
		     * unless the user expanded it there), and it is why a preset's share for this
		     * one column does not survive a load: the width is a preference, the
		     * arrangement is the layout.
		     * @returns nothing; the tree is changed through the service.
		     */
		    const reconcileNavigation = ()       => {
		      const view = frames.project()
		      const viewport = view.viewport?.width
		      if (viewport === undefined) return
		      const standing = navPane === undefined ? undefined : view.docked.find((pane) => pane.id === navPane)
		      if (standing !== undefined) {
		        const wanted = railWidth(viewport)
		        if (Math.abs(pxOf(standing, viewport) - wanted) > 1) frames.resizePane(standing.id, wanted / viewport)
		        return
		      }
		      navPane = undefined
		      if (view.docked.some((pane) => pane.content?.typeId === SIDEBAR_TYPE)) return
		      // The shell opens onto its content, so the frame the column goes beside is
		      // the centre rather than whatever is focused.
		      const centre = view.docked.find((pane) => pane.content?.typeId === CONVERSATION_TYPE)
		      const before = new Set(view.docked.map((pane) => pane.id))
		      // Not measured yet — the renderer may not have reported, or a preset may be
		      // mid-load. The next change tries again.
		      if (!frames.openContent(SIDEBAR_TYPE, { place: 'left' }).ok) return
		      const after = frames.project()
		      const width = after.viewport?.width
		      const rail = after.docked.find((pane) => !before.has(pane.id))
		      if (rail === undefined || width === undefined) return
		      navPane = rail.id
		      frames.resizePane(rail.id, railWidth(width) / width)
		      // Opening a frame focuses it, which would leave the caret on the navigation
		      // column. The shell opens onto its content, so focus goes back.
		      if (centre !== undefined) frames.focus(centre.id)
		    }

		    // The column is reconciled against the tree, so a close that got through is
		    // repaired by the change that carried it — the same way the right column
		    // treats a close it did not ask for.
		    reconcileNavigation()
		    const offNavigation = frames.subscribe(reconcileNavigation)
		    // The right column's seat is hosted on the overlay seat rather than in a
		    // frame's body, and that is the whole fix for a column that never appeared:
		    // a seat mounted by a body exists only while that frame does, and the frame
		    // is opened *because* the occupant reported it was shown — so the occupant
		    // could never make the first report. `frames.overlay` is drawn whether or not
		    // any frame exists, so the panel, its store and its reporting stay alive
		    // while nothing displays it, and the frame is left with one job: reserving
		    // the width.
		    //
		    // `shell.overlay` is declared on the same entry for the same reason and in
		    // the same place the shipped frame had it: the shell's own overlays do not
		    // belong to any frame either. `order: -1` keeps the entry under the other
		    // overlay entries, which is where the shipped stacking put the right column
		    // (below the shell's overlays, so a dialog still covers it).
		    //
		    // `id` is not decoration: this is a list seat, and the runtime refuses a list
		    // entry without one — `list slot "frames.overlay" requires options.id`.
		    const dropColumn = ctx.slots.inject('frames.overlay', () => ctx.slots.register({
		      name: 'frames.overlay',
		      id: 'legacy-overlay',
		      order: -1,
		      children: {
		        rightbar: { kind: 'single', scope: 'root' },
		        'shell.overlay': { kind: 'list', scope: 'root' },
		      },
		      inject: ()                        => ({ column }),
		    }, LegacyOverlay))
		    // Three frame bodies. Two of them declare the seat they draw into; the right
		    // column's declares nothing, because its seat belongs to the overlay entry
		    // above. Declaration is exclusive render authority, so two entries naming
		    // `sidebar` would be two claimants for one seat.
		    const dropBridge = ctx.slots.inject('frames.body', () => ctx.slots.register({
		      name: 'frames.body',
		      key: CONVERSATION_TYPE,
		      children: { main: { kind: 'keyed', scope: 'root' } },
		      // The selection reaches the bridge the way a seat hands its occupant extra
		      // props, rather than through the frame's own geometry.
		      inject: ()                 => ({ panels }),
		    }, LegacyConversation))
		    const dropSidebar = ctx.slots.inject('frames.body', () => ctx.slots.register({
		      name: 'frames.body',
		      key: SIDEBAR_TYPE,
		      children: { sidebar: { kind: 'single', scope: 'root' } },
		    }, LegacySidebar))
		    // The right column's frame reserves the width and draws nothing: the panel
		    // belongs to the seat above, which is mounted for as long as the content is
		    // rather than for as long as this frame is.
		    const dropRightbar = ctx.slots.inject('frames.body', () => ctx.slots.register({
		      name: 'frames.body',
		      key: RIGHTBAR_TYPE,
		    }, LegacyRightColumnPane))

		    const presenter = new ThemePresenter()
		    presenter.apply(ctx.theme.getTheme())
		    const offTheme = ctx.on('theme/change', (snapshot) => { presenter.apply(snapshot) })

		    return () => {
		      offTheme()
		      offNavigation()
		      presenter.dispose()
		      dropBridge()
		      offPanels()
		      dropSidebar()
		      dropRightbar()
		      dropColumn()
		      column.dispose()
		      // provide()'s disposer settles asynchronously; teardown is fire-and-forget.
		      void dropService()
		      dropPanelInfo()
		    }
		  }, 'frames-ui-compat: layout, panel info, theme, and the conversation bridge')
		}

		exports.inject = inject;
		exports.apply = apply;
		return module.exports;
	}
});
