// Generated by tools/build-client.ts — do not edit.
window.__ModuleLoader__.load({
	id: "@deepseek-ai/dsh-client-frames-ui-compat",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		// ---- packages/client/frames-ui-compat/src/client/facade.ts ----
		/**
		 * The `ctx.layout` facade.
		 *
		 * `ui-layout` cannot be edited, so this reproduces its runtime interface over the
		 * frame tree instead of migrating its consumers. `ui-workspace` and `ui-sidebar`
		 * inject the service and call into it; nothing about them changes.
		 *
		 * The facade is pure over a frame tree, so it is testable without a browser.
		 */

		/** What the facade needs from the frame tree. */
                               
                                       
                                    
                                 
 

		/** How the facade addresses the tree. */
                                      
                                                                                
                            
                                                                          
                                       
 

		/** The panel-navigation and geometry actions `ui-layout` exposed as `ctx.layout`. */
                               
                                           
                                
                       
                                                         
                       
 

		/**
		 * Build the facade.
		 *
		 * Two behaviours are load-bearing because the shipped implementation has them and
		 * its consumers may rely on either:
		 *
		 * - `selectPanel` with an unregistered id throws and leaves the current selection
		 *   alone, and
		 * - any accepted selection aborts the navigation signal a caller is holding,
		 *   which is how a pending navigation learns it lost.
		 * @param frames - the frame tree.
		 * @param options - the conversation's type id and the registry probe.
		 * @returns the facade.
		 */
		function createLayoutFacade(frames              , options                     )               {
		  let navigation                             

		  const beginNavigation = ()              => {
		    navigation?.abort()
		    navigation = new AbortController()
		    return navigation.signal
		  }

		  const selectPanel = (panelId               )       => {
		    if (panelId === null) {
		      frames.open(options.conversationTypeId)
		      beginNavigation()
		      return
		    }
		    if (!options.isRegistered(panelId)) {
		      // The shipped message names the panel and the id; consumers and the
		      // package's own specs both match on it.
		      throw new Error(`layout.selectPanel: main panel "${panelId}" is not registered`)
		    }
		    frames.open(panelId)
		    beginNavigation()
		  }

		  // The left and right columns are not frames yet, so the three geometry actions
		  // do nothing. They exist so a caller does not throw; a control that calls them
		  // is either not rendered or already gone.
		  return {
		    selectPanel,
		    beginNavigation,
		    toggleSidebar: () => {},
		    openRightbar: () => {},
		    closeRightbar: () => {},
		  }
		}

		// ---- packages/client/frames-ui-compat/src/client/theme-presenter.ts ----
		/**
		 * Theme presentation, reproduced from `ui-layout`.
		 *
		 * `ui-layout` owns the only code that writes a resolved theme snapshot to the
		 * document, and it cannot be edited, so disabling it would leave the page
		 * unthemed. This is that behaviour, copied rather than reinvented: pure DOM
		 * writes, no React path, and a retraction set so foreign attributes, metadata,
		 * and inline styles survive.
		 */
                                                                            

		/** Body attribute selecting the dark base palette in the token stylesheets. */
		const DARK_ATTRIBUTE = 'data-ds-dark-theme'

		/** Body variable carrying the user's content font size in px. */
		const CONTENT_FONT_SIZE_VARIABLE = '--dsh-content-font-size'

		/** Applies theme snapshots to the document; one instance per plugin fiber. */
		class ThemePresenter {
		  /** Token names written by the last apply, which is this presenter's retraction set. */
		          appliedTokens           = []
		  /** The single metadata node this presenter inserts and removes. */
		                   themeColorMeta                 

		  /** Create the presenter-owned metadata node before the first snapshot arrives. */
		  constructor() {
		    this.themeColorMeta = document.createElement('meta')
		    this.themeColorMeta.name = 'theme-color'
		  }

		  /**
		   * Project a snapshot onto the document.
		   * @param snapshot - resolved theme snapshot from `ctx.theme`.
		   */
		  apply(snapshot               )       {
		    const scheme = snapshot.active.colorScheme
		    document.documentElement.style.colorScheme = scheme
		    const body = document.body
		    if (scheme === 'dark') body.setAttribute(DARK_ATTRIBUTE, '')
		    else body.removeAttribute(DARK_ATTRIBUTE)
		    body.style.setProperty(CONTENT_FONT_SIZE_VARIABLE, `${snapshot.fontSize}px`)
		    for (const name of this.appliedTokens) body.style.removeProperty(name)
		    this.appliedTokens = []
		    for (const [name, value] of Object.entries(snapshot.active.tokens)) {
		      body.style.setProperty(name, value)
		      this.appliedTokens.push(name)
		    }
		    // Read the rendered background after the writes, so the palette stays the
		    // single colour authority.
		    this.themeColorMeta.content = getComputedStyle(body).backgroundColor
		    if (!this.themeColorMeta.isConnected) document.head.append(this.themeColorMeta)
		  }

		  /** Retract everything this presenter wrote, and only that. */
		  dispose()       {
		    document.documentElement.style.removeProperty('color-scheme')
		    const body = document.body
		    body.removeAttribute(DARK_ATTRIBUTE)
		    body.style.removeProperty(CONTENT_FONT_SIZE_VARIABLE)
		    for (const name of this.appliedTokens) body.style.removeProperty(name)
		    this.appliedTokens = []
		    this.themeColorMeta.remove()
		  }
		}

		// ---- packages/client/frames-ui-compat/src/client/index.ts ----
		/**
		 * The compatibility layer's plugin body.
		 *
		 * `ui-layout` cannot be edited, so this stands in for it: it provides
		 * `ctx.layout`, supplies the `usePanelInfo` standard prop, presents the theme to
		 * the document, and registers one frame body that declares `main` as its child.
		 *
		 * The last part is the bridge. A registration may declare child slots, so
		 * declaring `main` here makes `ui-conversation`'s existing
		 * `slots.inject('main', …)` fire and its panel render inside a frame — with no
		 * edit to `ui-conversation`.
		 */


		/** Services this plugin needs before it activates. */
		const inject = ['slots', 'theme', 'locale', 'frames']

		/** The frame type the bridge supplies, and the legacy key it answers to. */
		const CONVERSATION_TYPE = 'legacy.conversation'
		const CONVERSATION_KEY = 'conversation'

		/** The one panel-keyed field `usePanelInfo` publishes. */
                     
                              
 

		/** Props the bridge's component receives: the child renderer for `main`. */
                       
                                                                                
 

		/**
		 * The frame body that carries the conversation.
		 *
		 * It renders the legacy `main` key with the reserved `conversation` entry key,
		 * which is exactly what the shipped shell did.
		 * @param props - the child renderer for `main`.
		 * @returns the conversation panel.
		 */
		function LegacyConversation({ renderSlot }             )          {
		  return renderSlot('main', {}, { entryKey: CONVERSATION_KEY })
		}

		/**
		 * Register the compatibility layer.
		 * @param ctx - the client context.
		 */
		function apply(ctx   
                                                            
                 
          
                                                            
                                                           
                                          
   
                                                               
                                                                                                             
                                                                
                                                                            
                            
		 )       {
		  ctx.effect(() => {
		    const frames = ctx.get('frames')     
                                           
                                        
                                     
                                                                         
                                                 
     

		    frames.registerType({ id: CONVERSATION_TYPE, title: () => 'Conversation' })

		    // `ui-workspace` reads `activePanelId !== null` to know the centre is
		    // occupied by something other than the conversation. The published snapshot
		    // must keep its identity between changes: `useSyncExternalStore` compares by
		    // reference, so a freshly built object on every read would re-render forever.
		    const occupiedId = ()                => {
		      const active = frames.activeTypeId()
		      return active === undefined || active === CONVERSATION_TYPE ? null : active
		    }
		    let activePanelId = occupiedId()
		    let panelSnapshot            = { activePanelId }
		    const panelListeners = new Set            ()
		    const refresh = ()       => {
		      const next = occupiedId()
		      if (next === activePanelId) return
		      activePanelId = next
		      panelSnapshot = { activePanelId }
		      for (const listener of panelListeners) listener()
		    }
		    const offFrames = frames.subscribe(refresh)
		    const panelInfo = {
		      getSnapshot: ()            => panelSnapshot,
		      subscribe: (listener            )               => {
		        panelListeners.add(listener)
		        return () => { panelListeners.delete(listener) }
		      },
		    }

		    const facade = createLayoutFacade(frames, {
		      conversationTypeId: CONVERSATION_TYPE,
		      isRegistered: (typeId) => typeId === CONVERSATION_TYPE,
		    })

		    const dropPanelInfo = ctx.slots.provideRoot({ hooks: { panelInfo } })
		    const dropService = ctx.reflect.provide('layout', facade)
		    const dropBridge = ctx.slots.inject('frames.body', () => ctx.slots.register({
		      name: 'frames.body',
		      key: CONVERSATION_TYPE,
		      children: {
		        main: { kind: 'keyed', scope: 'root' },
		        sidebar: { kind: 'single', scope: 'root' },
		        rightbar: { kind: 'single', scope: 'root' },
		        'shell.overlay': { kind: 'list', scope: 'root' },
		      },
		    }, LegacyConversation))

		    const presenter = new ThemePresenter()
		    presenter.apply(ctx.theme.getTheme())
		    const offTheme = ctx.on('theme/change', (snapshot) => { presenter.apply(snapshot) })

		    return () => {
		      offTheme()
		      presenter.dispose()
		      dropBridge()
		      // provide()'s disposer settles asynchronously; teardown is fire-and-forget.
		      void dropService()
		      dropPanelInfo()
		      offFrames()
		    }
		  }, 'frames-ui-compat: layout, panel info, theme, and the conversation bridge')
		}

		exports.inject = inject;
		exports.apply = apply;
		return module.exports;
	}
});
