// Generated by tools/build-client.ts — do not edit.
window.__ModuleLoader__.load({
	id: "@deepseek-ai/dsh-client-frames-ui-compat",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		// ---- packages/client/frames-ui-compat/src/client/columns.ts ----
		/**
		 * The column geometry `ui-layout` used, restated.
		 *
		 * These are numbers, not types, so `import type` cannot reach them and a runtime
		 * import would drag in a package that is deliberately not mounted — `ui-layout`
		 * is disabled in this composition and its bundle pulls React in at module scope.
		 * So they are copied, and the copying is the thing to be careful about.
		 *
		 * Source, verified in the third-party tree: `packages/client/ui-layout/src/client/columns.ts`.
		 * Both the values and the rules they encode are that file's, and this file is
		 * where a divergence would have to be recorded.
		 *
		 * Where our model disagrees with theirs is deliberate and written down: our
		 * `minPaneSize` is 72px and the collapsed rail is 56px, so the rail is below the
		 * split minimum. It is not a violation — `minPaneSize` answers "can this pane be
		 * split into two usable halves", which is a different question from "how narrow
		 * may a column be told to be".
		 */

		/** Width before any user drag, in px. */
		const SIDEBAR_DEFAULT = 280

		/** Drag clamp floor, in px. */
		const SIDEBAR_MIN = 264

		/** Drag clamp ceiling, in px. */
		const SIDEBAR_MAX = 420

		/** The closed-sidebar rail: an icon column, in px. */
		const SIDEBAR_COLLAPSED = 56

		/** Below this, the column is drawn as the rail rather than as a full column. */
		const SIDEBAR_COLLAPSED_MAX = SIDEBAR_COLLAPSED

		/** Right column drag clamp floor, in px. */
		const RIGHTBAR_MIN = 300

		/** First-open right panel width, as a fraction of the frame. */
		const RIGHTBAR_DEFAULT_RATIO = 0.45

		/**
		 * Clamp a column width into the range the shipped shell allowed.
		 * @param px - the width asked for.
		 * @param min - the range floor.
		 * @param max - the range ceiling.
		 * @returns the clamped, whole-pixel width.
		 */
		function clampWidth(px        , min        , max        )         {
		  return Math.min(max, Math.max(min, Math.round(px)))
		}

		/**
		 * Whether a column of this width should be drawn as the compact rail.
		 * @param width - the column's rendered width in px.
		 * @returns whether the occupant should collapse.
		 */
		function isCollapsed(width        )          {
		  return width <= SIDEBAR_COLLAPSED_MAX
		}

		// ---- packages/client/frames-ui-compat/src/client/columns-body.ts ----
		/**
		 * The column frames: the two legacy seats that are columns rather than a centre.
		 *
		 * `ui-layout` drew a three-track grid — sidebar, centre, rightbar — and handed
		 * each column's occupant a share of the geometry it had solved. There is no grid
		 * here: each column is a frame, its area is the frame's area, and the width the
		 * occupant is told is that area measured against the viewport.
		 *
		 * That conversion is this file's whole job, and it has to be exact in both
		 * directions — a body is told how many pixels wide it is, and when the column is
		 * asked for a width the core is told the share of the parent that comes to.
		 */
                                                                                                     
                                                                  

		/** What a frame body is handed: what every renderer gives, plus its own children. */
                                                         
                                                                                  
 

		/**
		 * The left column.
		 *
		 * `ui-sidebar` is the only occupant. It reads `collapsed` to decide between the
		 * full column and the compact rail, and `width` to lay itself out — so both have
		 * to come from the frame the column is drawn in, which is why the renderer hands
		 * a body its own rectangle.
		 * @param props - the frame's area, the viewport, and the child renderer.
		 * @returns the sidebar seat, or nothing when no plugin has taken it.
		 */
		function LegacySidebar({ renderSlot, rect, viewport }                 )          {
		  const width = rect.width * viewport.width
		  const owner                    = { width, collapsed: isCollapsed(width) }
		  return renderSlot('sidebar', owner)
		}

		/**
		 * The right column.
		 *
		 * Unlike the sidebar this one is not always there: whether it is shown is the
		 * occupant's own recorded business, which it reports back through `ctx.layout`.
		 * So the body reports what the frame has room for and lets the occupant decide,
		 * exactly as the shipped grid did. The one difference is that here "not shown"
		 * can mean the frame is not in the tree at all.
		 * @param props - the frame's area, the viewport, and the child renderer.
		 * @returns the rightbar seat, or nothing when no plugin has taken it.
		 */
		function LegacyRightbar({ renderSlot, rect, viewport }                 )          {
		  const width = rect.width * viewport.width
		  const owner                     = {
		    width,
		    viewportWidth: viewport.width,
		    canShow: width >= RIGHTBAR_MIN,
		  }
		  return renderSlot('rightbar', owner)
		}

		// ---- packages/client/frames-ui-compat/src/client/facade.ts ----
		/**
		 * The `ctx.layout` facade.
		 *
		 * `ui-layout` cannot be edited, so this reproduces its runtime interface over the
		 * frame tree instead of migrating its consumers. `ui-workspace`, `ui-sidebar` and
		 * `ui-sidebar-right` inject the service and call into it; nothing about them
		 * changes.
		 *
		 * Two of the five calls need saying more precisely than the interface does:
		 *
		 * - `toggleSidebar()` toggles the sidebar between *collapsed* and *expanded*, not
		 *   between present and absent. In the shipped grid the column never disappeared:
		 *   it shrank to a 56px rail and the occupant drew a compact version of itself.
		 *   Here that is a frame whose share changes, so the frame — and with it every
		 *   seat `ui-sidebar` declares — stays mounted. That is what makes collapsing
		 *   safe, and it is the whole reason the content registry exists.
		 * - `openRightbar()` and `closeRightbar()` are **reports, not commands**. The
		 *   occupant decides whether it is shown and tells the frame how much room to
		 *   reserve; the interface says as much. So this facade takes the occupant at its
		 *   word: a report that it is shown opens the frame, a report that it is hidden
		 *   closes it.
		 *
		 * The facade is pure over a frame tree and a viewport, so it is testable without
		 * a browser.
		 */

		/** One docked frame as the facade reads it. */
                             
                     
                                           
                                                       
 

		/** What the facade needs from the frame tree. */
                               
                                       
                                                                                                
                                        
                                                               
                                    
                                                                             
                                  
                                                                                 
              
                                                                                      
                                          
   
 

		/** How the facade addresses the tree. */
                                      
                                                                                
                            
                                                   
                       
                                              
                        
 

		/** The panel-navigation and geometry actions `ui-layout` exposed as `ctx.layout`. */
                               
                                           
                                
                       
                                                         
                       
 

		/**
		 * Build the facade.
		 *
		 * Three behaviours are load-bearing because the shipped implementation has them
		 * and its consumers may rely on them:
		 *
		 * - `selectPanel` with an unregistered id throws and leaves the current selection
		 *   alone;
		 * - any accepted selection aborts the navigation signal a caller is holding,
		 *   which is how a pending navigation learns it lost;
		 * - the sidebar toggle flips the *collapsed* state, so a collapse followed by an
		 *   expand comes back to the width the user had chosen rather than to the default.
		 * @param frames - the frame tree.
		 * @param options - the type ids that play each column.
		 * @returns the facade.
		 */
		function createLayoutFacade(frames              , options                     )               {
		  let navigation                             

		  const beginNavigation = ()              => {
		    navigation?.abort()
		    navigation = new AbortController()
		    return navigation.signal
		  }

		  const selectPanel = (panelId               )       => {
		    if (panelId === null) {
		      frames.open(options.conversationTypeId)
		      beginNavigation()
		      return
		    }
		    if (!frames.hasType(panelId)) {
		      // The shipped message names the panel and the id; consumers and the
		      // package's own specs both match on it.
		      throw new Error(`layout.selectPanel: main panel "${panelId}" is not registered`)
		    }
		    frames.open(panelId)
		    beginNavigation()
		  }

		  /** The frame showing a type, and how many pixels wide it is. */
		  const column = (typeId        )                                            => {
		    const view = frames.project()
		    if (view.viewport === undefined) return undefined
		    const pane = view.docked.find((candidate) => candidate.tabs.some((tab) => tab.typeId === typeId))
		    return pane === undefined ? undefined : { id: pane.id, width: pane.rect.width * view.viewport.width }
		  }

		  /** The width the sidebar was last left at, so expanding restores the choice. */
		  let sidebarPreference = SIDEBAR_DEFAULT

		  const toggleSidebar = ()       => {
		    const view = frames.project()
		    const sidebar = column(options.sidebarTypeId)
		    if (view.viewport === undefined || sidebar === undefined) return

		    if (!isCollapsed(sidebar.width)) sidebarPreference = sidebar.width
		    const wanted = isCollapsed(sidebar.width)
		      ? clampWidth(sidebarPreference, SIDEBAR_MIN, SIDEBAR_MAX)
		      : SIDEBAR_COLLAPSED
		    // The core is told a share of the parent split; the caller is the only side
		    // that knows the viewport, so it does the division.
		    frames.resizePane(sidebar.id, wanted / view.viewport.width)
		  }

		  const openRightbar = (track         , _fullscreen         )       => {
		    const view = frames.project()
		    if (view.viewport === undefined) return
		    if (column(options.rightbarTypeId) !== undefined) return
		    // Beside the centre when it can take a track, which is what the shipped
		    // column was: an extra track on the right rather than a pane of the centre.
		    const centre = view.docked.find((pane) => pane.tabs.some((tab) => tab.typeId === options.conversationTypeId))
		    const beside = track ? centre?.id : undefined
		    frames.openContent(options.rightbarTypeId, {
		      place: 'right',
		      ...beside === undefined ? {} : { beside },
		    })
		  }

		  const closeRightbar = ()       => {
		    const pane = column(options.rightbarTypeId)
		    // The occupant decides when it is shown; this only carries the decision out.
		    if (pane !== undefined) frames.close(pane.id)
		  }

		  return { selectPanel, beginNavigation, toggleSidebar, openRightbar, closeRightbar }
		}

		// ---- packages/client/frames-ui-compat/src/client/theme-presenter.ts ----
		/**
		 * Theme presentation, reproduced from `ui-layout`.
		 *
		 * `ui-layout` owns the only code that writes a resolved theme snapshot to the
		 * document, and it cannot be edited, so disabling it would leave the page
		 * unthemed. This is that behaviour, copied rather than reinvented: pure DOM
		 * writes, no React path, and a retraction set so foreign attributes, metadata,
		 * and inline styles survive.
		 */
                                                                            

		/** Body attribute selecting the dark base palette in the token stylesheets. */
		const DARK_ATTRIBUTE = 'data-ds-dark-theme'

		/** Body variable carrying the user's content font size in px. */
		const CONTENT_FONT_SIZE_VARIABLE = '--dsh-content-font-size'

		/** Applies theme snapshots to the document; one instance per plugin fiber. */
		class ThemePresenter {
		  /** Token names written by the last apply, which is this presenter's retraction set. */
		          appliedTokens           = []
		  /** The single metadata node this presenter inserts and removes. */
		                   themeColorMeta                 

		  /** Create the presenter-owned metadata node before the first snapshot arrives. */
		  constructor() {
		    this.themeColorMeta = document.createElement('meta')
		    this.themeColorMeta.name = 'theme-color'
		  }

		  /**
		   * Project a snapshot onto the document.
		   * @param snapshot - resolved theme snapshot from `ctx.theme`.
		   */
		  apply(snapshot               )       {
		    const scheme = snapshot.active.colorScheme
		    document.documentElement.style.colorScheme = scheme
		    const body = document.body
		    if (scheme === 'dark') body.setAttribute(DARK_ATTRIBUTE, '')
		    else body.removeAttribute(DARK_ATTRIBUTE)
		    body.style.setProperty(CONTENT_FONT_SIZE_VARIABLE, `${snapshot.fontSize}px`)
		    for (const name of this.appliedTokens) body.style.removeProperty(name)
		    this.appliedTokens = []
		    for (const [name, value] of Object.entries(snapshot.active.tokens)) {
		      body.style.setProperty(name, value)
		      this.appliedTokens.push(name)
		    }
		    // Read the rendered background after the writes, so the palette stays the
		    // single colour authority.
		    this.themeColorMeta.content = getComputedStyle(body).backgroundColor
		    if (!this.themeColorMeta.isConnected) document.head.append(this.themeColorMeta)
		  }

		  /** Retract everything this presenter wrote, and only that. */
		  dispose()       {
		    document.documentElement.style.removeProperty('color-scheme')
		    const body = document.body
		    body.removeAttribute(DARK_ATTRIBUTE)
		    body.style.removeProperty(CONTENT_FONT_SIZE_VARIABLE)
		    for (const name of this.appliedTokens) body.style.removeProperty(name)
		    this.appliedTokens = []
		    this.themeColorMeta.remove()
		  }
		}

		// ---- packages/client/frames-ui-compat/src/client/index.ts ----
		/**
		 * The compatibility layer's plugin body.
		 *
		 * `ui-layout` cannot be edited, so this stands in for it: it provides
		 * `ctx.layout`, supplies the `usePanelInfo` standard prop, presents the theme to
		 * the document, and registers one frame body that declares `main` as its child.
		 *
		 * The last part is the bridge. A registration may declare child slots, so
		 * declaring `main` here makes `ui-conversation`'s existing
		 * `slots.inject('main', …)` fire and its panel render inside a frame — with no
		 * edit to `ui-conversation`.
		 */




		/** Services this plugin needs before it activates. */
		const inject = ['slots', 'theme', 'locale', 'frames']

		/** The frame types the bridge supplies, and the legacy keys they answer to. */
		const CONVERSATION_TYPE = 'legacy.conversation'
		const CONVERSATION_KEY = 'conversation'
		const SIDEBAR_TYPE = 'legacy.sidebar'
		const RIGHTBAR_TYPE = 'legacy.rightbar'

		/** The one panel-keyed field `usePanelInfo` publishes. */
                     
                              
 

		/** Props the bridge's component receives: the child renderer for `main`. */
                       
                                                                                
 

		/**
		 * The frame body that carries the conversation.
		 *
		 * It renders the legacy `main` key with the reserved `conversation` entry key,
		 * which is exactly what the shipped shell did.
		 * @param props - the child renderer for `main`.
		 * @returns the conversation panel.
		 */
		function LegacyConversation({ renderSlot }             )          {
		  return renderSlot('main', {}, { entryKey: CONVERSATION_KEY })
		}

		/**
		 * Register the compatibility layer.
		 * @param ctx - the client context.
		 */
		function apply(ctx   
                                                            
                 
          
                                                            
                                                           
                                          
   
                                                               
                                                                                                             
                                                                
                                                                            
                            
		 )       {
		  ctx.effect(() => {
		    const frames = ctx.get('frames')     
                                           
                                                                                                    
                                            
                                            
                                                                   
                                        
                                     
                                      
                                                                         
                                                                                            
                                                 
                  
                                                                                          
                                   
                             
                                                   
                                                               
           
       
     
		    frames.registerType({ id: CONVERSATION_TYPE, title: () => 'Conversation' })
		    frames.registerType({ id: SIDEBAR_TYPE, title: () => 'Navigation' })
		    frames.registerType({ id: RIGHTBAR_TYPE, title: () => 'Right panel' })
		    // A column has to be able to exist with no frame showing it — the sidebar is
		    // closed by shrinking to the rail, and the right panel is closed by its
		    // occupant deciding so. Registering the contents up front is what lets either
		    // come back without being recreated.
		    frames.registerContent({ id: SIDEBAR_TYPE, kind: SIDEBAR_TYPE, title: 'Navigation' })
		    frames.registerContent({ id: RIGHTBAR_TYPE, kind: RIGHTBAR_TYPE, title: 'Right panel' })

		    // `ui-workspace` reads `activePanelId !== null` to know the centre is
		    // occupied by something other than the conversation. The published snapshot
		    // must keep its identity between changes: `useSyncExternalStore` compares by
		    // reference, so a freshly built object on every read would re-render forever.
		    const occupiedId = ()                => {
		      const active = frames.activeTypeId()
		      return active === undefined || active === CONVERSATION_TYPE ? null : active
		    }
		    let activePanelId = occupiedId()
		    let panelSnapshot            = { activePanelId }
		    const panelListeners = new Set            ()
		    const refresh = ()       => {
		      const next = occupiedId()
		      if (next === activePanelId) return
		      activePanelId = next
		      panelSnapshot = { activePanelId }
		      for (const listener of panelListeners) listener()
		    }
		    const offFrames = frames.subscribe(refresh)
		    const panelInfo = {
		      getSnapshot: ()            => panelSnapshot,
		      subscribe: (listener            )               => {
		        panelListeners.add(listener)
		        return () => { panelListeners.delete(listener) }
		      },
		    }

		    const facade = createLayoutFacade(frames, {
		      conversationTypeId: CONVERSATION_TYPE,
		      sidebarTypeId: SIDEBAR_TYPE,
		      rightbarTypeId: RIGHTBAR_TYPE,
		    })

		    const dropPanelInfo = ctx.slots.provideRoot({ hooks: { panelInfo } })
		    const dropService = ctx.reflect.provide('layout', facade)

		    // The sidebar goes up with the shell. `ui-sidebar` cannot put its own column
		    // there — it renders into a seat, and a seat needs a frame to be drawn in —
		    // so whoever owns the column types owns the opening. This is that: the
		    // composition, which is the only layer that knows these three types exist.
		    //
		    // The right column is deliberately *not* opened here. Whether it is shown is
		    // its occupant's recorded business, and it says so through `ctx.layout`; the
		    // shipped shell opened onto no right column either.
		    //
		    // The core default is still one frame. A profile that mounts no compatibility
		    // layer gets exactly that, which is what "one frame with nothing configured"
		    // has always meant.
		    const seedColumns = ()       => {
		      const centre = frames.project().docked
		        .find((pane) => pane.tabs.some((tab) => tab.typeId === CONVERSATION_TYPE))
		      const brought = frames.openContent(SIDEBAR_TYPE, { place: 'left' })
		      if (!brought.ok) return
		      const view = frames.project()
		      if (view.viewport === undefined) return
		      const column = view.docked.find((pane) => pane.tabs.some((tab) => tab.typeId === SIDEBAR_TYPE))
		      if (column !== undefined) frames.resizePane(column.id, SIDEBAR_DEFAULT / view.viewport.width)
		      // Opening a frame focuses it, which would leave the caret on the navigation
		      // column at boot. The shell opens onto its content, so focus goes back.
		      if (centre !== undefined) frames.focus(centre.id)
		    }

		    // Seeding needs the renderer's measurements, and the two plugins mount in an
		    // order this one does not control — so it tries, and keeps trying until the
		    // frame is measured, rather than assuming the renderer got there first.
		    let seeded = false
		    const trySeed = ()       => {
		      if (seeded) return
		      const before = frames.project().docked.length
		      seedColumns()
		      if (frames.project().docked.length > before) seeded = true
		    }
		    trySeed()
		    const offSeed = frames.subscribe(trySeed)
		    // Three bodies, three seats. Each frame declares the seat it draws into and
		    // nothing else — declaration is exclusive render authority, so two entries
		    // naming `sidebar` would be two claimants for one seat.
		    const dropBridge = ctx.slots.inject('frames.body', () => ctx.slots.register({
		      name: 'frames.body',
		      key: CONVERSATION_TYPE,
		      children: {
		        main: { kind: 'keyed', scope: 'root' },
		        'shell.overlay': { kind: 'list', scope: 'root' },
		      },
		    }, LegacyConversation))
		    const dropSidebar = ctx.slots.inject('frames.body', () => ctx.slots.register({
		      name: 'frames.body',
		      key: SIDEBAR_TYPE,
		      children: { sidebar: { kind: 'single', scope: 'root' } },
		    }, LegacySidebar))
		    const dropRightbar = ctx.slots.inject('frames.body', () => ctx.slots.register({
		      name: 'frames.body',
		      key: RIGHTBAR_TYPE,
		      children: { rightbar: { kind: 'single', scope: 'root' } },
		    }, LegacyRightbar))

		    const presenter = new ThemePresenter()
		    presenter.apply(ctx.theme.getTheme())
		    const offTheme = ctx.on('theme/change', (snapshot) => { presenter.apply(snapshot) })

		    return () => {
		      offTheme()
		      offSeed()
		      presenter.dispose()
		      dropBridge()
		      dropSidebar()
		      dropRightbar()
		      // provide()'s disposer settles asynchronously; teardown is fire-and-forget.
		      void dropService()
		      dropPanelInfo()
		      offFrames()
		    }
		  }, 'frames-ui-compat: layout, panel info, theme, and the conversation bridge')
		}

		exports.inject = inject;
		exports.apply = apply;
		return module.exports;
	}
});
